export enum Role {
  OPERATOR = 'OPERATOR',
  SUPERVISOR = 'SUPERVISOR',
  ADMINISTRATOR = 'ADMINISTRATOR',
  ATENAS_CLIENT = 'ATENAS_CLIENT',
  EURODAC_CLIENT = 'EURODAC_CLIENT',
  MBI_CLIENT = 'MBI_CLIENT',
}
