services:
  auth: 'AuthMockService'
  user: 'UserRepositoryMockService'
  documentScanner: 'DocumentScannerService'
backend:
  clientService: 'http://localhost:3001'
  backend: 'https://localhost:7526'
