services:
  auth: 'AuthService'
  user: 'UserRepositoryMockService'
  documentScanner: 'DocumentScannerMockService'
  case: 'CaseRepositoryRemoteService'
backend:
  url: 'https://localhost:7526'
clientService:
  url: 'http://localhost:3001'
