services:
  auth: 'AuthMockService'
  user: 'UserRepositoryMockService'
  auxiliar: 'AuxiliarRepositoryMockService'
  case: 'CaseRepositoryMockService'
backend:
  url: 'https://localhost:7526'
clientService:
  url: 'http://localhost:3001'
