export enum ActivityType {
  CONSULTATION = 'CONSULTATION',
  RESOLUTION = 'RESOLUTION',
  FACE_VERIFICATION_AUTOMATIC = 'FACE_VERIFICATION_AUTOMATIC',
  DOCUMENT_VERIFICATION_AUTOMATIC = 'DOCUMENT_VERIFICATION_AUTOMATIC',
}

export enum CaseStatus {
  OPEN = 'OPEN',
  PENDING = 'PENDING',
  SOLVED = 'SOLVED',
  CLARIFICATION_PENDING = 'CLARIFICATION_PENDING',
  ARCHIVED = 'ARCHIVED',
}

export enum CaseResolution {
  PENDING = 'PENDING',
  WITH_EVIDENCES = 'WITH_EVIDENCES',
  WITHOUT_EVIDENCES = 'WITHOUT_EVIDENCES',
  INVALID_DOCUMENT = 'INVALID_DOCUMENT',
  INSUFFICIENT_QUALITY = 'INSUFFICIENT_QUALITY',
}

export enum AttachmentType {
  DOCUMENT_IDV = 'DOCUMENT_IDV',
  DOCUMENT_DV = 'DOCUMENT_DV',
  DIGITAL = 'DIGITAL',
}

export enum DigitalAttachmentType {
  GENERIC = 'GENERIC',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO', 
  PHOTO = 'PHOTO',
  FACIAL = 'FACIAL',
  OTHER = 'OTHER',
}

export enum DocumentAttachmentType {
  TD1 = 'TD1',
  TD2 = 'TD2',
  TD3 = 'TD3',
}

export enum NotificationType {
  ARCHIVE = 'ARCHIVE',
  SLA_TIMEOUT = 'SLA_TIMEOUT',
  ASSIGMENT_TIMEOUT = 'ASSIGMENT_TIMEOUT',
  SOLVED = 'SOLVED',
  CLARIFICATION_PENDING = 'CLARIFICATION_PENDING',
}
